### ISSUE TITLE
parse error syntax error, upon fresh insall

### ISSUE THREAD

**Issue by MagedEWilliam** [mahdiyazdani/Hypermarket#1]
just by installing the theme, the whole site crashes,

The server(Hostgator) PHP version: 5.4.23

`Parse error: syntax error, unexpected T_FUNCTION in path\wordpress\wp-content\themes\Hypermarket-master\includes\classes\class-customizer.php on line 69`

**Comment by mahdiyazdani** [comment]
Hello @MagedEWilliam 

Thanks for raising this question.

This error usually happens because of using Windows based hosting account with an old PHP version on it (Released: 12 Dec 2013).

Consider upgrading your current account to Linux based hosting with PHP 7.0.0 and above.

For your reference, please visit [Hostgator's support page](http://support.hostgator.com/articles/what-version-of-php-are-you-using).
